# Generated by Django 2.2.6 on 2019-10-18 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_site_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='timespamp',
            new_name='timestamp',
        ),
    ]
