# Generated by Django 2.2.6 on 2019-10-23 08:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_auto_20191018_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ошибка скрапинга',
                'verbose_name_plural': 'Ошибки скрапинга',
                'ordering': ['-timestamp'],
            },
        ),
    ]
